/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistematurnos.igu;

/**
 *
 * @author PC 1
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoGrandeInicio = new javax.swing.JLabel();
        txtTituloBienvenidaInicio = new javax.swing.JLabel();
        txtSubtituloInicio = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 221, 221), 1, true));
        setPreferredSize(new java.awt.Dimension(1040, 560));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 560));

        logoGrandeInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoInicio-40%-400x360.png"))); // NOI18N

        txtTituloBienvenidaInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTituloBienvenidaInicio.setForeground(new java.awt.Color(74, 163, 223));
        txtTituloBienvenidaInicio.setText("Bienvenido a MawClinic");

        txtSubtituloInicio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtSubtituloInicio.setForeground(new java.awt.Color(153, 153, 153));
        txtSubtituloInicio.setText("Administre médicos, pacientes y turnos de forma centralizada ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(txtTituloBienvenidaInicio)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSubtituloInicio)
                    .addComponent(logoGrandeInicio))
                .addGap(313, 313, 313))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(txtTituloBienvenidaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSubtituloInicio)
                .addGap(36, 36, 36)
                .addComponent(logoGrandeInicio)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 1038, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 558, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoGrandeInicio;
    private javax.swing.JLabel txtSubtituloInicio;
    private javax.swing.JLabel txtTituloBienvenidaInicio;
    // End of variables declaration//GEN-END:variables
}
